#!/bin/bash
if [ ` cat "/etc/apt/sources.list" | grep "backports" ` ];
then echo repository exists
else apt-add-repository 'deb http://ru.archive.ubuntu.com/ubuntu/ jammy-backports multiverse restricted universe main'
fi

echo installing applications...
sudo apt-get install -y update
sudo apt-get install -y python3
sudo apt-get install -y ca-certificates curl gnupg
sudo apt-get install -y vim
sudo apt install -y cron
sudo sudo snap install -y pycharm-community --classic
sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo apt install -y apache2
sudo ufw allow 'Apache'
sudo apt-get install -y openssh-server
sudo systemctl enable ssh
sudo systemctl start ssh
